/**
 * Avolites Titan training rig fixtures — Robe personalities extracted from the
 * official 'Titan training v10' show file (© Avolites Ltd.). Channel maps are the
 * real Titan charts mapped to our functions (CMY/framing land on 'control' as our
 * engine is additive-RGB only).
 */
import type { FixtureDefinition } from './types'

export const AVOLITES_TRAINING_FIXTURES: FixtureDefinition[] = [
  {
    id: 'robe-robin-bmfl-blade',
    manufacturer: 'Robe',
    model: 'Robin BMFL Blade',
    category: 'movingHead',
    source: 'builtin',
    modes: [
      { name: 'Mode 1', channels: [
        { name: 'Pan', function: 'pan', defaultValue: 128, highlightValue: 128 },
        { name: 'Pan Fine', function: 'panFine', defaultValue: 0, fine: true },
        { name: 'Tilt', function: 'tilt', defaultValue: 128, highlightValue: 128 },
        { name: 'Tilt Fine', function: 'tiltFine', defaultValue: 0, fine: true },
        { name: 'P/T Speed', function: 'control', defaultValue: 0 },
        { name: 'Control', function: 'control', defaultValue: 0 },
        { name: 'Colour 1', function: 'colorWheel', defaultValue: 0 },
        { name: 'Colour 1 Fine', function: 'control', defaultValue: 0, fine: true },
        { name: 'Colour 2', function: 'colorWheel', defaultValue: 0 },
        { name: 'Colour 2 Fine', function: 'control', defaultValue: 0, fine: true },
        { name: 'Cyan', function: 'control', defaultValue: 0 },
        { name: 'Magenta', function: 'control', defaultValue: 0 },
        { name: 'Yellow', function: 'control', defaultValue: 0 },
        { name: 'CTO', function: 'colorTemp', defaultValue: 0 },
        { name: 'CMY Macro', function: 'control', defaultValue: 0 },
        { name: 'Effect Speed', function: 'control', defaultValue: 0 },
        { name: 'Colour Time', function: 'colorWheel', defaultValue: 0 },
        { name: 'Beam Time', function: 'control', defaultValue: 0 },
        { name: 'Graphic Position', function: 'control', defaultValue: 0 },
        { name: 'Graphic Rot', function: 'control', defaultValue: 0 },
        { name: 'Graphic Anim', function: 'control', defaultValue: 0 },
        { name: 'Gobo 1', function: 'gobo', defaultValue: 0 },
        { name: 'Gobo 2', function: 'gobo', defaultValue: 0 },
        { name: 'Gobo 2 Rot', function: 'goboRotation', defaultValue: 0 },
        { name: 'Gobo 2 Rot Fine', function: 'control', defaultValue: 0, fine: true },
        { name: 'Prism', function: 'prism', defaultValue: 0 },
        { name: 'Prism Rot', function: 'goboRotation', defaultValue: 0 },
        { name: 'Frost', function: 'iris', defaultValue: 0 },
        { name: 'Iris', function: 'iris', defaultValue: 0 },
        { name: 'Iris Fine', function: 'control', defaultValue: 0, fine: true },
        { name: 'Zoom', function: 'zoom', defaultValue: 0 },
        { name: 'Zoom Fine', function: 'control', defaultValue: 0, fine: true },
        { name: 'Focus', function: 'focus', defaultValue: 0 },
        { name: 'Focus Fine', function: 'control', defaultValue: 0, fine: true },
        { name: 'Reserved', function: 'control', defaultValue: 0 },
        { name: 'Blade All Rot', function: 'control', defaultValue: 0 },
        { name: 'Blade 1', function: 'control', defaultValue: 0 },
        { name: 'Blade 1 Rot', function: 'control', defaultValue: 0 },
        { name: 'Blade 2', function: 'control', defaultValue: 0 },
        { name: 'Blade 2 Rot', function: 'control', defaultValue: 0 },
        { name: 'Blade 3', function: 'control', defaultValue: 0 },
        { name: 'Blade 3 Rot', function: 'control', defaultValue: 0 },
        { name: 'Blade 4', function: 'control', defaultValue: 0 },
        { name: 'Blade 4 Rot', function: 'control', defaultValue: 0 },
        { name: 'Blade Macro', function: 'control', defaultValue: 0 },
        { name: 'Blade Mac Spd', function: 'control', defaultValue: 0 },
        { name: 'Shutter', function: 'shutter', defaultValue: 255, highlightValue: 255 },
        { name: 'Dimmer', function: 'dimmer', defaultValue: 0, highlightValue: 255 },
        { name: 'Dimmer Fine', function: 'control', defaultValue: 0, fine: true },
      ] },
    ],
  },
  {
    id: 'robe-robin-100-ledbeam',
    manufacturer: 'Robe',
    model: 'Robin 100 LEDBeam',
    category: 'movingHead',
    source: 'builtin',
    modes: [
      { name: 'Mode 3, 14 DMX', channels: [
        { name: 'Pan', function: 'pan', defaultValue: 128, highlightValue: 128 },
        { name: 'Pan Fine', function: 'panFine', defaultValue: 0, fine: true },
        { name: 'Tilt', function: 'tilt', defaultValue: 128, highlightValue: 128 },
        { name: 'Tilt Fine', function: 'tiltFine', defaultValue: 0, fine: true },
        { name: 'P/T Speed', function: 'control', defaultValue: 0 },
        { name: 'Control', function: 'control', defaultValue: 0 },
        { name: 'Red', function: 'red', defaultValue: 0 },
        { name: 'Green', function: 'green', defaultValue: 0 },
        { name: 'Blue', function: 'blue', defaultValue: 0 },
        { name: 'White', function: 'white', defaultValue: 0 },
        { name: 'CTO', function: 'colorTemp', defaultValue: 0 },
        { name: 'Colour Macros', function: 'colorWheel', defaultValue: 0 },
        { name: 'Shutter', function: 'shutter', defaultValue: 255, highlightValue: 255 },
        { name: 'Dimmer', function: 'dimmer', defaultValue: 0, highlightValue: 255 },
      ] },
    ],
  },
  {
    id: 'robe-robin-colorstrobe',
    manufacturer: 'Robe',
    model: 'Robin ColorStrobe',
    category: 'strobe',
    source: 'builtin',
    modes: [
      { name: 'Mode 1', channels: [
        { name: 'Red', function: 'red', defaultValue: 0 },
        { name: 'Green', function: 'green', defaultValue: 0 },
        { name: 'Blue', function: 'blue', defaultValue: 0 },
        { name: 'White', function: 'white', defaultValue: 0 },
        { name: 'CTO', function: 'colorTemp', defaultValue: 0 },
        { name: 'Colour Macro', function: 'colorWheel', defaultValue: 0 },
        { name: 'Dimmer', function: 'dimmer', defaultValue: 0, highlightValue: 255 },
        { name: 'Duration', function: 'control', defaultValue: 0 },
        { name: 'Shutter', function: 'shutter', defaultValue: 255, highlightValue: 255 },
      ] },
    ],
  },
]
